//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsdElektronik.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_urunler()
        {
            this.tbl_stok = new HashSet<tbl_stok>();
        }
    
        public int id { get; set; }
        public string UrunAd { get; set; }
        public Nullable<short> UrunFiyat { get; set; }
        public Nullable<short> UrunKategori { get; set; }
        public string UrunFoto { get; set; }
        public string UrunAciklama { get; set; }
        public string UrunKod { get; set; }
    
        public virtual tbl_kategori tbl_kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_stok> tbl_stok { get; set; }
    }
}
