//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsdElektronik.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stok
    {
        public int id { get; set; }
        public int UrunId { get; set; }
        public Nullable<short> StokSayi { get; set; }
    
        public virtual tbl_urunler tbl_urunler { get; set; }
    }
}
